const path = require('path');
const crypto = require('crypto');
const bcrypt = require('bcryptjs');
const XLSX = require('xlsx');
const { pool } = require('../config/db');

const SHEET_NAME = 'Chapter Data';
const IMPORT_KEY = 'chapter-business-dataset';
const DEFAULT_PASSWORD = '123456';

const columns = {
  serial: 'S.no',
  candidateName: 'Candidate name',
  chapterDesignation: 'Chapter Designation',
  companyName: 'Company Name',
  companyDesignation: 'Company Designation',
  companyLocation: 'Company Location',
  services: 'Services Provided by the company',
  chapterName: 'Chapter name',
  chapterMembers: 'Total members in the chapter',
  referralsGiven: 'Referrals given by him/her',
  referralsReceived: 'Referrals received by him/her',
  revenue: 'Total Revenue Generated by him/her',
  chapterBusiness: 'Total business generated by his/her chapter',
  chapterReferrals: 'Total referrals generated in the chapter',
  chapterMeetings: 'Total meetings conducted in the chapter',
  meetingsAttended: 'Total meetings attended',
  chapterRegion: 'Chapter region',
};

const normalizeText = (value) => String(value ?? '').trim();
const toNumber = (value) => {
  const parsed = Number(String(value ?? '').replace(/,/g, '').trim());
  return Number.isFinite(parsed) ? parsed : 0;
};

const slug = (value) => normalizeText(value)
  .toLowerCase()
  .replace(/[^a-z0-9]+/g, '.')
  .replace(/(^\.|\.$)/g, '') || 'member';

const employeeIdFor = (serial) => `GSN${String(serial || '').padStart(4, '0')}`;

const emailFor = (name, serial) => `${slug(name)}.${String(serial || '').padStart(4, '0')}@import.gsn.network`;

const rowHash = (row) => crypto.createHash('sha256').update(JSON.stringify(row)).digest('hex');

const roleForDesignation = (designation) => (
  normalizeText(designation).toLowerCase() === 'president' ? 'CHAPTER_PRESIDENT' : 'NORMAL_USER'
);

const workbookRows = (filePath) => {
  const workbook = XLSX.readFile(filePath, { cellDates: true });
  const sheetName = workbook.SheetNames.includes(SHEET_NAME) ? SHEET_NAME : workbook.SheetNames[0];
  const worksheet = workbook.Sheets[sheetName];
  if (!worksheet) {
    return { sheetName, rows: [], workbook };
  }
  return {
    sheetName,
    rows: XLSX.utils.sheet_to_json(worksheet, { defval: null, raw: false }),
    workbook,
  };
};

const analyzeChapterWorkbook = (filePath) => {
  const { sheetName, rows, workbook } = workbookRows(filePath);
  const chapters = new Map();
  const designations = new Map();
  const regions = new Map();

  rows.forEach((row) => {
    const chapter = normalizeText(row[columns.chapterName]) || 'Unassigned';
    const designation = normalizeText(row[columns.chapterDesignation]) || 'Unassigned';
    const region = normalizeText(row[columns.chapterRegion]) || 'Unassigned';
    chapters.set(chapter, (chapters.get(chapter) || 0) + 1);
    designations.set(designation, (designations.get(designation) || 0) + 1);
    regions.set(region, (regions.get(region) || 0) + 1);
  });

  return {
    sourceFile: filePath,
    sheets: workbook.SheetNames.map((name) => ({
      name,
      range: workbook.Sheets[name]['!ref'],
      selected: name === sheetName,
    })),
    selectedSheet: sheetName,
    totalRows: rows.length,
    columns: rows[0] ? Object.keys(rows[0]) : [],
    chapters: Array.from(chapters, ([name, count]) => ({ name, count })),
    designations: Array.from(designations, ([name, count]) => ({ name, count })),
    regions: Array.from(regions, ([name, count]) => ({ name, count })),
    sample: rows.slice(0, 3),
  };
};

const validateRow = (row, index) => {
  const errors = [];
  if (!normalizeText(row[columns.candidateName])) errors.push('Candidate name is required.');
  if (!normalizeText(row[columns.chapterName])) errors.push('Chapter name is required.');
  if (!normalizeText(row[columns.chapterDesignation])) errors.push('Chapter designation is required.');
  return {
    valid: errors.length === 0,
    rowNumber: Number(row[columns.serial]) || index + 2,
    errors,
  };
};

const importChapterWorkbook = async (filePath, startedBy) => {
  const absolutePath = path.resolve(filePath);
  const analysis = analyzeChapterWorkbook(absolutePath);
  const rows = workbookRows(absolutePath).rows;
  const passwordHash = await bcrypt.hash(DEFAULT_PASSWORD, 12);
  const client = await pool.connect();

  const counters = {
    totalRows: rows.length,
    validRows: 0,
    invalidRows: 0,
    insertedUsers: 0,
    updatedUsers: 0,
    insertedChapters: 0,
    updatedChapters: 0,
  };

  try {
    await client.query('BEGIN');

    const { rows: logRows } = await client.query(`
      INSERT INTO import_logs (import_key, source_filename, status, total_rows, started_by, metadata)
      VALUES ($1, $2, 'STARTED', $3, $4, $5)
      RETURNING id
    `, [IMPORT_KEY, absolutePath, counters.totalRows, startedBy || null, JSON.stringify(analysis)]);
    const importLogId = logRows[0].id;

    const validRows = [];
    for (const [index, row] of rows.entries()) {
      const validation = validateRow(row, index);
      if (!validation.valid) {
        counters.invalidRows += 1;
        await client.query(`
          INSERT INTO import_errors (import_log_id, row_number, message, row_data)
          VALUES ($1, $2, $3, $4)
        `, [importLogId, validation.rowNumber, validation.errors.join(' '), JSON.stringify(row)]);
        continue;
      }
      counters.validRows += 1;
      validRows.push({ row, rowNumber: validation.rowNumber });
    }

    const chapterMap = new Map();
    const firstPresidentByChapter = new Map();

    validRows.forEach(({ row, rowNumber }) => {
      const chapterName = normalizeText(row[columns.chapterName]);
      if (!chapterMap.has(chapterName)) {
        chapterMap.set(chapterName, {
          name: chapterName,
          city: 'Imported',
          region: normalizeText(row[columns.chapterRegion]) || 'Imported',
          reported_member_count: toNumber(row[columns.chapterMembers]),
          total_business_generated_inr: toNumber(row[columns.chapterBusiness]),
          total_referrals_generated: toNumber(row[columns.chapterReferrals]),
          total_meetings_conducted: toNumber(row[columns.chapterMeetings]),
        });
      }
      if (roleForDesignation(row[columns.chapterDesignation]) === 'CHAPTER_PRESIDENT' && !firstPresidentByChapter.has(chapterName)) {
        firstPresidentByChapter.set(chapterName, employeeIdFor(rowNumber));
      }
    });

    const chapterIds = new Map();
    for (const chapter of chapterMap.values()) {
      const { rows: existing } = await client.query('SELECT id FROM chapters WHERE name = $1', [chapter.name]);
      const { rows: upserted } = await client.query(`
        INSERT INTO chapters (name, city, region, country, import_key)
        VALUES ($1, $2, $3, 'India', $4)
        ON CONFLICT (name) DO UPDATE SET
          city = EXCLUDED.city,
          region = EXCLUDED.region,
          import_key = EXCLUDED.import_key,
          updated_at = NOW()
        RETURNING id
      `, [chapter.name, chapter.city, chapter.region, IMPORT_KEY]);
      existing.length ? counters.updatedChapters += 1 : counters.insertedChapters += 1;
      chapterIds.set(chapter.name, upserted[0].id);
    }

    const userIdsByEmployee = new Map();
    for (const { row, rowNumber } of validRows) {
      const employeeId = employeeIdFor(rowNumber);
      const chapterName = normalizeText(row[columns.chapterName]);
      const chapterId = chapterIds.get(chapterName);
      const role = roleForDesignation(row[columns.chapterDesignation]);
      const { rows: existing } = await client.query('SELECT id FROM users WHERE employee_id = $1', [employeeId]);
      const { rows: upserted } = await client.query(`
        INSERT INTO users (
          employee_id, full_name, email, password_hash, role, status, member_category,
          chapter_designation, company_name, company_designation, company_location,
          region, chapter_id, total_referrals, referrals_received, business_generated_inr,
          meetings_attended, import_key
        )
        VALUES ($1, $2, $3, $4, $5, 'ACTIVE', $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
        ON CONFLICT (employee_id) DO UPDATE SET
          full_name = EXCLUDED.full_name,
          email = EXCLUDED.email,
          role = EXCLUDED.role,
          status = 'ACTIVE',
          member_category = EXCLUDED.member_category,
          chapter_designation = EXCLUDED.chapter_designation,
          company_name = EXCLUDED.company_name,
          company_designation = EXCLUDED.company_designation,
          company_location = EXCLUDED.company_location,
          region = EXCLUDED.region,
          chapter_id = EXCLUDED.chapter_id,
          total_referrals = EXCLUDED.total_referrals,
          referrals_received = EXCLUDED.referrals_received,
          business_generated_inr = EXCLUDED.business_generated_inr,
          meetings_attended = EXCLUDED.meetings_attended,
          import_key = EXCLUDED.import_key,
          updated_at = NOW()
        RETURNING id
      `, [
        employeeId,
        normalizeText(row[columns.candidateName]),
        emailFor(row[columns.candidateName], rowNumber),
        passwordHash,
        role,
        normalizeText(row[columns.services]),
        normalizeText(row[columns.chapterDesignation]),
        normalizeText(row[columns.companyName]),
        normalizeText(row[columns.companyDesignation]),
        normalizeText(row[columns.companyLocation]),
        normalizeText(row[columns.chapterRegion]),
        chapterId,
        toNumber(row[columns.referralsGiven]),
        toNumber(row[columns.referralsReceived]),
        toNumber(row[columns.revenue]),
        toNumber(row[columns.meetingsAttended]),
        IMPORT_KEY,
      ]);
      existing.length ? counters.updatedUsers += 1 : counters.insertedUsers += 1;
      userIdsByEmployee.set(employeeId, upserted[0].id);

      await client.query(`
        INSERT INTO import_source_rows (import_key, row_number, user_id, chapter_id, row_hash, raw_data)
        VALUES ($1, $2, $3, $4, $5, $6)
        ON CONFLICT (import_key, row_number) DO UPDATE SET
          user_id = EXCLUDED.user_id,
          chapter_id = EXCLUDED.chapter_id,
          row_hash = EXCLUDED.row_hash,
          raw_data = EXCLUDED.raw_data,
          imported_at = NOW()
      `, [IMPORT_KEY, rowNumber, upserted[0].id, chapterId, rowHash(row), JSON.stringify(row)]);
    }

    for (const [chapterName, presidentEmployeeId] of firstPresidentByChapter.entries()) {
      const presidentId = userIdsByEmployee.get(presidentEmployeeId);
      const chapterId = chapterIds.get(chapterName);
      if (!presidentId || !chapterId) continue;
      await client.query('UPDATE chapters SET president_id = $1, updated_at = NOW() WHERE id = $2', [presidentId, chapterId]);
      await client.query(`
        UPDATE users
        SET president_id = CASE WHEN id = $1 THEN NULL ELSE $1 END,
            updated_at = NOW()
        WHERE chapter_id = $2
      `, [presidentId, chapterId]);
    }

    for (const [chapterName, chapter] of chapterMap.entries()) {
      await client.query(`
        INSERT INTO chapter_analytics (
          chapter_id, reported_member_count, total_business_generated_inr,
          total_referrals_generated, total_meetings_conducted, source_import_id, updated_at
        )
        VALUES ($1, $2, $3, $4, $5, $6, NOW())
        ON CONFLICT (chapter_id) DO UPDATE SET
          reported_member_count = EXCLUDED.reported_member_count,
          total_business_generated_inr = EXCLUDED.total_business_generated_inr,
          total_referrals_generated = EXCLUDED.total_referrals_generated,
          total_meetings_conducted = EXCLUDED.total_meetings_conducted,
          source_import_id = EXCLUDED.source_import_id,
          updated_at = NOW()
      `, [
        chapterIds.get(chapterName),
        chapter.reported_member_count,
        chapter.total_business_generated_inr,
        chapter.total_referrals_generated,
        chapter.total_meetings_conducted,
        importLogId,
      ]);
    }

    await client.query(`
      UPDATE import_logs
      SET status = 'COMPLETED',
          valid_rows = $2,
          invalid_rows = $3,
          inserted_users = $4,
          updated_users = $5,
          inserted_chapters = $6,
          updated_chapters = $7,
          completed_at = NOW()
      WHERE id = $1
    `, [
      importLogId,
      counters.validRows,
      counters.invalidRows,
      counters.insertedUsers,
      counters.updatedUsers,
      counters.insertedChapters,
      counters.updatedChapters,
    ]);

    await client.query('COMMIT');
    return { importLogId, ...counters, analysis };
  } catch (err) {
    await client.query('ROLLBACK');
    throw err;
  } finally {
    client.release();
  }
};

module.exports = {
  analyzeChapterWorkbook,
  importChapterWorkbook,
  IMPORT_KEY,
};
